### ISSUE TITLE
Not working on ubuntu

### ISSUE THREAD

**Issue by metehus** [anabastos/daledale#5]
Not working on Ubuntu 20.04, with this error message:

```
matheus@matheus:~/Downloads$ npx daledale
npx: installed 1 in 0.758s
Error: Command failed: paplay /home/matheus/.npm/_npx/7023/lib/node_modules/daledale/daledale.ogg
Connection failure: Connection refused
pa_context_connect() failed: Connection refused

    at ChildProcess.exithandler (child_process.js:303:12)
    at ChildProcess.emit (events.js:315:20)
    at maybeClose (internal/child_process.js:1021:16)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:286:5) {
  killed: false,
  code: 1,
  signal: null,
  cmd: 'paplay /home/matheus/.npm/_npx/7023/lib/node_modules/daledale/daledale.ogg'
}

```

**Comment by onepushmain** [comment]
Hello @metehus ! 

The problem isn't the package, but the **audio execution in Linux**. Most likely your Ubuntu **does not have** any audio driver or sound servers (like PulseAudio). Check [this.](https://itsfoss.com/fix-sound-ubuntu-1304-quick-tip/)

If you running your **ubuntu in a VM**, do not forget to take a look in the **Audio Section in VirtualBox** and verify if the driver is [set correctly.](https://askubuntu.com/questions/811116/no-sound-in-ubuntu-16-04-lts-in-virtualbox#:~:text=In%20Ubuntu%20first%20click%20on,in%20this%20picture%3A%20Sound%20Settings)

But, if you running your **Ubuntu in a WSL/WSL2**, you can use this [tutorial](https://discourse.ubuntu.com/t/getting-sound-to-work-on-wsl2/11869) to use pulseaudio in your Windows with WSL2.
